FROM isaac-ros AS sfg-go2

# dockerfile-utils: ignore
WORKDIR ${HOME}/dependencies

# Agilex PiPER
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \ 
    sudo apt update && sudo apt install -y --no-install-recommends \
        ethtool \
        can-utils && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    pip install \
        python-can \
        piper-sdk

# Intel RealSense SDK 2.0
RUN export CUDACXX="/usr/local/cuda/bin/nvcc" && \
    export PATH=${PATH}:"/usr/local/cuda/bin" && \
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:"/usr/local/cuda/lib64" && \
    git clone -b "v2.56.3" --depth 1 "https://github.com/IntelRealSense/librealsense.git" && \
    cd "librealsense" && \
    cmake -B "build" \
        -DBUILD_EXAMPLES=true \
        -DBUILD_WITH_CUDA=true \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_PYTHON_BINDINGS=bool:true \
        -DPYTHON_EXECUTABLE=$(which python) && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig && \
    sudo cp "../config/99-realsense-libusb.rules" "/etc/udev/rules.d/" && \
    sudo udevadm control --reload-rules && udevadm trigger || true

# ROS Wrapper for Intel RealSense SDK 2.0
RUN rosdep update && \
    git clone -b "4.56.3" --depth 1 "https://github.com/IntelRealSense/realsense-ros.git" && \
    cd "realsense-ros" && \
    \
    for package in "realsense2_camera_msgs" "realsense2_description" "realsense2_camera"; do \
        cd "${package}" && \
        # Generate debian files.
        bloom-generate rosdebian && \
        # Use all cores for building.
        sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
        # Ignore missing info for shlibdeps if applicable.
        sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
        # Remove librealsense2 dependency only for realsense2_camera.
        if [[ "${package}" == "realsense2_camera" ]]; then \
            sed -i 's/ros-humble-librealsense2, //g' "debian/control"; \
        fi; \
        # Build the package.
        fakeroot "debian/rules" binary && \
        # Install the package.
        cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb"; \
    done; \
    \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

# Unitree SDK2
RUN git clone -b "main" --depth 1 "https://gitlab+deploy-token-36:gldt-1njKp-oSkbndAzYDGjGu@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/unitree-sdk-2.git" "unitree_sdk2" && \
    cd "unitree_sdk2" && \
    cmake -B "build" \
        -DCMAKE_BUILD_TYPE=Release && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig

# Livox SDK2
RUN git clone -b "v1.2.5" --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git" && \
    cd "Livox-SDK2" && \
    cmake -B "build" \
        -DCMAKE_BUILD_TYPE=Release && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig

# Livox ROS Driver 2
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-pcl-conversions && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    rosdep update && \
    git clone -b "main" --depth 1 "https://gitlab+deploy-token-28:gldt-Fnui4V-UxTzsHFDmgarX@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/livox-ros-driver-2.git" "livox_ros_driver_2" && \
    cd "livox_ros_driver_2" && \
    # Generate debian files.
    bloom-generate rosdebian && \
    # Use all cores for building.
    sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
    # Ignore missing info for shlibdeps if applicable.
    sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
    # Build the package.
    fakeroot "debian/rules" binary && \
    # Install the package.
    cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

# Lighthouse tracking
RUN git clone -b "main" --depth 1 "https://gitlab+deploy-token-31:gldt-T4mZXdX4seq-farZKKWv@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/libsurvive.git" && \
    cd "libsurvive" && \
    cmake -B "build" \
        -DCMAKE_BUILD_TYPE=Release && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig

# Additional ROS packages
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-ros2-control \
        ros-${ROS_DISTRO}-ros2-controllers \
        ros-${ROS_DISTRO}-isaac-ros-jetson-stats && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

RUN sudo rm -rf "${HOME}/dependencies"

WORKDIR ${WORKSPACE_DIRECTORY}

CMD "${REPOSITORY_DIRECTORY}/.devcontainer/scripts/post_start_command" && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    source "${REPOSITORY_DIRECTORY}/colcon_ws/install/setup.bash" && \
    ros2 launch sfg_go2 "go2.launch.py"