FROM sfg-agent-devcontainer AS sfg-go2

WORKDIR ${HOME}/dependencies

# Unitree SDK2
RUN git clone -b "main" --depth 1 "https://gitlab+deploy-token-36:gldt-1njKp-oSkbndAzYDGjGu@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/unitree-sdk-2.git" "unitree_sdk2" && \
    cd "unitree_sdk2" && \
    cmake -B "build" \
        -DCMAKE_BUILD_TYPE=Release && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig

# Intel RealSense SDK 2.0
RUN git clone -b "v2.58.2" --depth 1 "https://github.com/IntelRealSense/librealsense.git" && \
    cd "librealsense" && \
    cmake -B "build" \
        -DBUILD_EXAMPLES=false \
        -DBUILD_GRAPHICAL_EXAMPLES=false \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_PYTHON_BINDINGS=bool:true \
        -DPYTHON_EXECUTABLE=$(which python) && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig

# ROS Wrapper for Intel RealSense SDK 2.0
RUN rosdep update && \
    git clone -b "4.58.2" --depth 1 "https://github.com/IntelRealSense/realsense-ros.git" && \
    cd "realsense-ros" && \
    \
    for package in "realsense2_camera_msgs" "realsense2_description" "realsense2_camera"; do \
        cd "${package}" && \
        # Generate debian files.
        bloom-generate rosdebian && \
        # Use all cores for building.
        sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
        # Ignore missing info for shlibdeps if applicable.
        sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
        # Remove librealsense2 dependency only for realsense2_camera.
        if [[ "${package}" == "realsense2_camera" ]]; then \
            sed -i "s/ros-${ROS_DISTRO}-librealsense2, //g" "debian/control"; \
        fi; \
        # Build the package.
        fakeroot "debian/rules" binary && \
        # Install the package.
        cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb"; \
    done && \
    \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

# Livox SDK2
RUN git clone -b "v1.3.1" --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git" && \
    cd "Livox-SDK2" && \
    cmake -B "build" \
        -DCMAKE_BUILD_TYPE=Release \
        # cstdint is no longer included by default in Ubuntu 24.04's version of gcc, so we need to add it manually.
        -DCMAKE_CXX_FLAGS="-include cstdint" && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig

# Livox ROS Driver 2
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-pcl-conversions && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    rosdep update && \
    git clone -b "main" --depth 1 "https://gitlab+deploy-token-28:gldt-Fnui4V-UxTzsHFDmgarX@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/livox-ros-driver-2.git" "livox_ros_driver_2" && \
    cd "livox_ros_driver_2" && \
    # Generate debian files.
    bloom-generate rosdebian && \
    # Use all cores for building.
    sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
    # Ignore missing info for shlibdeps if applicable.
    sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
    # Build the package.
    fakeroot "debian/rules" binary && \
    # Install the package.
    cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

# Agilex PiPER
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        can-utils \
        ethtool&& \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    pip install --break-system-packages \
        piper-sdk \
        python-can

RUN sudo rm -rf "${HOME}/dependencies"

WORKDIR ${WORKSPACE_DIRECTORY}

CMD "${REPOSITORY_DIRECTORY}/.devcontainer/scripts/post_start_command" && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    cd "${REPOSITORY_DIRECTORY}/colcon_ws" && \
    source "install/setup.bash" && \
    ros2 launch sfg_go2_bringup "bringup.launch.py"