services:
  container:
    build:
      context: "../.."
      dockerfile: ".devcontainer/dockerfile"
      args:
        - PLATFORM=${PLATFORM}
        - REPOSITORY_DIRECTORY=${REPOSITORY_DIRECTORY}
        - WORKSPACE_DIRECTORY=${WORKSPACE_DIRECTORY}
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    volumes:
      - type: bind
        source: "../.."
        target: "${REPOSITORY_DIRECTORY}"
      - type: bind
        source: "${SELECTED_DIRECTORY}"
        target: "${MOUNT_POINT}"
      - type: bind
        source: "/dev"
        target: "/dev"
      - type: bind
        source: "/etc/localtime"
        target: "/etc/localtime"
        read_only: true
    environment:
      - REPOSITORY_DIRECTORY=${REPOSITORY_DIRECTORY}
      - WORKSPACE_DIRECTORY=${WORKSPACE_DIRECTORY}
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    ipc: host
    runtime: nvidia
