/**:
  ros__parameters:
    serial_no: "728312070152"
    publish_tf: true
    base_frame_id: base_frame

    enable_infra1: false
    enable_infra2: false
    enable_sync: true
    align_depth.enable: true

    # Color stream settings.
    enable_color: true
    color_qos: SENSOR_DATA
    color_info_qos: SENSOR_DATA
    rgb_camera.color_profile: 1280x720x15
    # Use h264 hardware accelerated encoding for color stream.
    camera_head.color.image_raw.ffmpeg.encoder: h264_nvmpi
    # Use a group of picture size of 1 to reduce latency. This will result in
    # every single frame being a keyframe, which trades off some compression
    # efficiency for lower latency.
    camera_head.color.image_raw.ffmpeg.gop_size: 1
    camera_head.color.image_raw.ffmpeg.bit_rate: 3000000
    camera_head.color.image_raw.ffmpeg.encoder_av_options: profile:high,preset:ultrafast
    camera_head.color.image_raw.enable_pub_plugins:
      - image_transport/ffmpeg
      - image_transport/raw

    # Depth stream settings.
    enable_depth: true
    depth_qos: SENSOR_DATA
    depth_info_qos: SENSOR_DATA
    depth_module.depth_profile: 1280x720x15
    # Use rvl compression instead of png for depth images because it is faster and
    # png seems to end up using the same hardware resources as the color stream,
    # thefore increasing latency for the color stream.
    .camera_head.aligned_depth_to_color.image_raw.compressedDepth.format: rvl
    camera_head.aligned_depth_to_color.image_raw.enable_pub_plugins:
      - image_transport/compressedDepth
      - image_transport/raw
    camera_head.depth.image_rect_raw.enable_pub_plugins:
      - image_transport/raw
