#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e
# Create dedicated directory for dependencies.
mkdir -p "${HOME}/dependencies"

# Agilex PiPER
sudo apt update && sudo apt install -y --no-install-recommends \
    ethtool \
    can-utils

pip install \
    python-can \
    piper-sdk

# Intel RealSense SDK 2.0
cd "${HOME}/dependencies"

export CUDACXX="/usr/local/cuda/bin/nvcc"
export PATH=${PATH}:"/usr/local/cuda/bin"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:"/usr/local/cuda/lib64"

git clone -b "v2.56.3" --depth 1 "https://github.com/IntelRealSense/librealsense.git"
cd "librealsense"
mkdir "build" && cd "build"
cmake ".." \
    -DBUILD_EXAMPLES=true \
    -DBUILD_WITH_CUDA=true \
    -DCMAKE_BUILD_TYPE=release \
    -DBUILD_PYTHON_BINDINGS=bool:true \
    -DPYTHON_EXECUTABLE=$(which python)
sudo make -j$(nproc) install
sudo cp "../config/99-realsense-libusb.rules" "/etc/udev/rules.d/"
sudo udevadm control --reload-rules && udevadm trigger || true

# ROS Wrapper for Intel RealSense SDK 2.0
rosdep update

export DEB_BUILD_OPTIONS="parallel=$(nproc)"

cd "${HOME}/dependencies"
git clone "https://github.com/IntelRealSense/realsense-ros.git" -b "4.56.3"
cd "realsense-ros/realsense2_camera_msgs" && bloom-generate rosdebian && fakeroot "debian/rules" binary
cd ".." && sudo apt-get install -y ./*.deb
cd "realsense2_description" && bloom-generate rosdebian && fakeroot "debian/rules" binary
cd ".." && sudo apt-get install -y ./*.deb
cd "realsense2_camera" && bloom-generate rosdebian && sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && sed -i 's/ros-humble-librealsense2, //g' "debian/control" && fakeroot "debian/rules" binary
cd ".." && sudo apt-get install -y ./*.deb

unset DEB_BUILD_OPTIONS

# CycloneDDS
cd "${HOME}/dependencies"
git clone -b "releases/0.10.x" --depth 1 "https://github.com/eclipse-cyclonedds/cyclonedds.git"
cd "cyclonedds"
mkdir "build" "install" && cd "build"
cmake ".."
cmake --build "."
sudo cmake --build "." --target install

# Unitree SDK2
cd "${HOME}/dependencies"
git clone --depth 1 "https://github.com/unitreerobotics/unitree_sdk2.git"
cd "unitree_sdk2"
mkdir "build" && cd "build"
cmake ".."
make -j$(nproc)
sudo make install

# Unitree SDK2 Python
cd "${HOME}/dependencies"
git clone --depth 1 "https://github.com/unitreerobotics/unitree_sdk2_python.git"
cd "unitree_sdk2_python"
CMAKE_PREFIX_PATH=/usr/local pip install "."

# Livox SDK2
cd "${HOME}/dependencies"
git clone --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git"
cd "Livox-SDK2"
mkdir "build" && cd "build"
cmake ".."
make -j$(nproc)
sudo make install

sudo rm -rf "${HOME}/dependencies"

# Isaac ROS packages
sudo apt update && sudo apt install -y --no-install-recommends \
    ros-${ROS_DISTRO}-isaac-ros-h264-decoder \
    ros-${ROS_DISTRO}-isaac-ros-h264-encoder \
    ros-${ROS_DISTRO}-isaac-ros-jetson-stats
