#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e
# Create dedicated directory for dependencies.
mkdir -p "${HOME}/dependencies"

# Agilex PiPER
pip install \
    python-can \
    piper_sdk

# Intel RealSense SDK 2.0
if [[ "${PLATFORM}" == "arm64" ]]; then
    sudo apt-key adv --keyserver "keyserver.ubuntu.com" --recv-key "F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE" || sudo apt-key adv --keyserver "hkp://keyserver.ubuntu.com:80" --recv-key "F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE"
    sudo add-apt-repository -y "deb "https://librealsense.intel.com/Debian/apt-repo" $(lsb_release -cs) main" -u
    sudo apt update && sudo apt install -y --no-install-recommends \
        librealsense2-utils \
        librealsense2-dev
else
    sudo mkdir -p "/etc/apt/keyrings"
    curl -sSf "https://librealsense.intel.com/Debian/librealsense.pgp" | sudo tee "/etc/apt/keyrings/librealsense.pgp" > "/dev/null"
    echo "deb [signed-by="/etc/apt/keyrings/librealsense.pgp"] "https://librealsense.intel.com/Debian/apt-repo" `lsb_release -cs` main" | \
    sudo tee "/etc/apt/sources.list.d/librealsense.list"
    sudo apt update && sudo apt install -y --no-install-recommends \
        librealsense2-dkms \
        librealsense2-utils \
        librealsense2-dev \
        librealsense2-dbg
fi

# CycloneDDS
cd "${HOME}/dependencies"
git clone -b "releases/0.10.x" --depth 1 "https://github.com/eclipse-cyclonedds/cyclonedds.git"
cd "cyclonedds"
mkdir "build" "install"
cd "build"
cmake ".." -DCMAKE_INSTALL_PREFIX="../install"
cmake --build "." --target install

export CYCLONEDDS_HOME="${HOME}/dependencies/cyclonedds/install"
echo "export CYCLONEDDS_HOME=${CYCLONEDDS_HOME}" >> "${HOME}/.bashrc"

# Unitree SDK2
cd "${HOME}/dependencies"
git clone --depth 1 "https://github.com/unitreerobotics/unitree_sdk2.git"
cd "unitree_sdk2"
mkdir "build"
cd "build"
cmake ".."
sudo make install

# Unitree SDK2 Python
cd "${HOME}/dependencies"
git clone --depth 1 "https://github.com/unitreerobotics/unitree_sdk2_python.git"
cd "unitree_sdk2_python"
pip install -e "."

# Livox SDK2
cd "${HOME}/dependencies"
git clone --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git"
cd "Livox-SDK2"
mkdir "build"
cd "build"
cmake ".." && make -j
sudo make install

# Isaac ROS packages
sudo apt update && sudo apt install -y --no-install-recommends \
    ros-${ROS_DISTRO}-isaac-ros-h264-encoder \
    ros-${ROS_DISTRO}-isaac-ros-jetson-stats \
    ros-${ROS_DISTRO}-isaac-ros-realsense
