#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "${SCRIPT_DIR}/env_file_utils"

set_up_mounted_directory() {
  echo Set up a directory to be mounted inside the dev container.
  echo -e "\033[1;33mNote that if you change the directory to be mounted, you will need to rebuild the container for the changes to take effect.\033[0m"

  local ENVIRONMENT_VARIABLE="SELECTED_DIRECTORY"
  local VALUE=$(get_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}")

  if [[ ! -z "${VALUE}" ]]; then
    local MESSAGE="The directory '${VALUE}' has previously been selected for mounting. Would you like to choose a different directory? [y/N] "
    read -p "${MESSAGE}" CONFIRM && [[ $CONFIRM == y ]] || return
  fi

  # Allow the developer to choose a directory of their choice to mount.
  read -p "Enter a directory to mount: " VALUE

  # Check if the user canceled directory selection.
  if [[ -z "${VALUE}" ]]; then
    echo Error: Directory selection canceled.
    exit 1
  fi

  # Check if the provided directory exists.
  if [[ ! -d "${VALUE}" ]]; then
    echo Error: The directory does not exist.
    exit 1
  fi

  # Save the selected directory in an environment variable. This will later be leveraged
  # by the docker-compose.yml to mount the specified directory inside the container.
  set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${VALUE}"
}

forward_env_variables() {
  for VAR in "${@}"; do
    # Extract variable name (before '=').
    local ENVIRONMENT_VARIABLE=${VAR%%=*}
    # Extract variable value (after '=').
    local VALUE=${VAR#*=}

    set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${VALUE}"
  done
}

forward_timezone() {
  local ENVIRONMENT_VARIABLE="TZ"
  set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "$(cat /etc/timezone)"
}

forward_user() {
  set_environment_variable "${ENVIRONMENT_FILE}" "HOST_USERNAME" "${USER}"
  set_environment_variable "${ENVIRONMENT_FILE}" "HOST_USER_UID" "$(id -u ${USER})"
  set_environment_variable "${ENVIRONMENT_FILE}" "HOST_USER_GID" "$(id -g ${USER})"
}

forward_host_arch() {
  case $(uname -m) in
    "x86_64")
      HOST_ARCH="amd64"
      ;;
    "aarch64" | "arm64")
      HOST_ARCH="arm64"
      ;;
    *)
      echo "Unsupported architecture: $(uname -m)" >&2
      exit 1
      ;;
  esac

  set_environment_variable "${ENVIRONMENT_FILE}" "HOST_ARCH" "${HOST_ARCH}"
}

ENVIRONMENT_FILE="${SCRIPT_DIR}/../.env"

set_up_mounted_directory
forward_env_variables ${@}
forward_timezone
forward_user
forward_host_arch
