#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "${SCRIPT_DIR}/env_file_utils"
source "${SCRIPT_DIR}/print_utils"

ENVIRONMENT_FILE="${SCRIPT_DIR}/../.env"

set_up_mounted_directory() {
  print_info "> Set up a directory to be mounted inside the dev container."
  print_warning "Note that if you change the directory to be mounted, you will need to rebuild the container for the changes to take effect."

  local ENVIRONMENT_VARIABLE="SELECTED_DIRECTORY"
  local VALUE=$(get_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}")

  if [[ ! -z "${VALUE}" ]]; then
    local MESSAGE="The directory '${VALUE}' has previously been selected for mounting. Would you like to choose a different directory? [y/N] "
    read -p "${MESSAGE}" CONFIRM 
    
    if [[ ! $CONFIRM == y ]]; then
      print_info "< Done setting up a directory to be mounted inside the dev container."
      return
    fi
  fi

  # Allow the developer to choose a directory of their choice to mount.
  read -p "Enter a directory to mount: " VALUE

  # Check if the user canceled directory selection.
  if [[ -z "${VALUE}" ]]; then
    print_error "Error: Directory selection canceled."
    exit 1
  fi

  # Check if the provided directory exists.
  if [[ ! -d "${VALUE}" ]]; then
    print_error "Error: The directory does not exist."
    exit 1
  fi

  # Save the selected directory in an environment variable. This will later be leveraged
  # by the docker-compose.yml to mount the specified directory inside the container.
  set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${VALUE}"
  print_info "< Done setting up a directory to be mounted inside the dev container."
}

forward_environment_variables() {
  print_info "> Forwarding environment variables."

  for VAR in "${@}"; do
    # Extract variable name (before '=').
    local ENVIRONMENT_VARIABLE=${VAR%%=*}
    # Extract variable value (after '=').
    local VALUE=${VAR#*=}

    set_environment_variable "${ENVIRONMENT_FILE}" "${ENVIRONMENT_VARIABLE}" "${VALUE}"
  done

  print_info "< Done forwarding environment variables."
}

forward_user() {
  print_info "> Forwarding user."
  set_environment_variable "${ENVIRONMENT_FILE}" "USERNAME" "${USER}"
  set_environment_variable "${ENVIRONMENT_FILE}" "USER_UID" "$(id -u ${USER})"
  set_environment_variable "${ENVIRONMENT_FILE}" "USER_GID" "$(id -g ${USER})"
  print_info "< Done forwarding user."
}

forward_platform() {
  print_info "> Forwarding platform."

  case $(uname -m) in
    "x86_64")
      PLATFORM="amd64"
      ;;
    "aarch64" | "arm64")
      PLATFORM="arm64"
      ;;
    *)
      print_error "Unsupported architecture: $(uname -m)" >&2
      exit 1
      ;;
  esac

  set_environment_variable "${ENVIRONMENT_FILE}" "PLATFORM" "${PLATFORM}"
  print_info "< Done forwarding platform."
}

forward_jtop_gid()
{
  print_info "> Forwarding jtop GID."

  if [ -S "/run/jtop.sock" ]; then
      set_environment_variable "${ENVIRONMENT_FILE}" "JTOP_GID" "$(stat -c %g /run/jtop.sock)"
  fi

  print_info "< Done jtop GID."
}

print_plain ""
set_up_mounted_directory
forward_environment_variables ${@}
forward_user
forward_platform
forward_jtop_gid
