#!/bin/bash -e

indent() { 
    sed 's/^/  /'
}

print_color() {
    tput bold
    tput setaf ${1}
    echo "${2}"
    tput sgr0
}

print_error() {
    print_color 1 "${1}"
}

print_warning() {
    print_color 3 "${1}"
}

print_info() {
    print_color 2 "${1}"
}

print_plain() {
    echo "${1}"
}