FROM heiis/ros2-ml:humble-desktop-full-torch2.4.0

# Use bash as shell.
SHELL ["/bin/bash", "-c"]

ARG CONTAINER_DEPENDENCIES_DIRECTORY CONTAINER_REPOSITORY_DIRECTORY CONTAINER_WORKSPACE_DIRECTORY

USER root

#########################################################################################################
# Set timezone.                                                                                         #
#########################################################################################################
RUN --mount=type=cache,target="/var/cache/apt" \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        tzdata && \
    apt -y autoremove && apt clean autoclean && rm -rf "/var/lib/apt/lists/*"

#########################################################################################################
# Update and install required apt and pip dependencies.                                                 #
#########################################################################################################
RUN --mount=type=cache,target="/var/cache/apt" \
    apt update && apt-get install -y --no-install-recommends --allow-downgrades \
        iproute2 \
        usbutils \
        python3-colcon-mixin \
        v4l-utils \
        # Fix taken from "https://github.com/IntelRealSense/realsense-ros/issues/3203" for error during colcon build: 
        # The imported target "opencv_core" references the file "/usr/lib/libopencv_core.so.4.8.0" but this file does not exist.
        libopencv-dev=4.5.4+dfsg-9ubuntu4 && \
    apt -y autoremove && apt clean autoclean && rm -rf "/var/lib/apt/lists/*"

RUN pip install \
        python-can \
        piper_sdk

#########################################################################################################
# Set up Additional dependencies.                                                                       #
#########################################################################################################

# Intel RealSense SDK 2.0
RUN --mount=type=cache,target="/var/cache/apt" \
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE && \
    sudo add-apt-repository -y "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u && \
    apt update && apt-get install -y --no-install-recommends \
        librealsense2-utils \
        librealsense2-dev \
        ros-${ROS_DISTRO}-realsense2-* && \
    apt -y autoremove && apt clean autoclean && rm -rf "/var/lib/apt/lists/*"

# CycloneDDS
RUN mkdir -p "${CONTAINER_DEPENDENCIES_DIRECTORY}" && cd "${CONTAINER_DEPENDENCIES_DIRECTORY}" && \
    git clone -b "releases/0.10.x" --depth 1 "https://github.com/eclipse-cyclonedds/cyclonedds"  && \
    cd "cyclonedds" && \
    mkdir "build" "install" && \
    cd "build" && \
    cmake ".." -DCMAKE_INSTALL_PREFIX="../install" && \
    cmake --build "." --target install

ENV CYCLONEDDS_HOME="${CONTAINER_DEPENDENCIES_DIRECTORY}/cyclonedds/install"

# Unitree SDK2
RUN cd "${CONTAINER_DEPENDENCIES_DIRECTORY}" && \
    git clone --depth 1 "https://github.com/unitreerobotics/unitree_sdk2.git" && \
    cd "unitree_sdk2" && \
    mkdir "build" && \
    cd "build" && \
    cmake ".." && \
    make install

# Unitree SDK2 Python
RUN cd "${CONTAINER_DEPENDENCIES_DIRECTORY}" && \
    git clone --depth 1 "https://github.com/unitreerobotics/unitree_sdk2_python.git" && \
    cd "unitree_sdk2_python" && \
    pip install -e "."

# Livox SDK2
RUN cd "${CONTAINER_DEPENDENCIES_DIRECTORY}" && \
    git clone --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git" && \
    cd "Livox-SDK2" && \
    mkdir "build" && \
    cd "build" && \
    cmake ".." && make -j && \
    make install

#########################################################################################################
# Create a non-root user:                                                                               #
# - https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user.  #
#########################################################################################################
ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

RUN --mount=type=cache,target=/var/cache/apt \
    groupadd --gid "${USER_GID}" "${USERNAME}" && \
    useradd --uid "${USER_UID}" --gid "${USER_GID}" -m "${USERNAME}" && \
    usermod -aG video,plugdev,sudo,root ${USERNAME} && \
    apt-get update && \
    apt-get install -y \
        sudo && \
    sudo apt -y autoremove && sudo apt clean autoclean && sudo rm -rf "/var/lib/apt/lists/*" && \
    echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/${USERNAME}" && \
    chmod 0440 "/etc/sudoers.d/${USERNAME}"

# Activate the previously created user.
USER ${USERNAME}
# Set our working directory.
WORKDIR ${CONTAINER_WORKSPACE_DIRECTORY}
# Ensure we can read/write to the working directory.
RUN sudo chmod a+rwx "."

ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

#########################################################################################################
# Setup ROS2.                                                                                           #
#########################################################################################################
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> "${HOME}/.bashrc" && \
    ln -s "${CONTAINER_REPOSITORY_DIRECTORY}/.devcontainer/.vscode" "${CONTAINER_WORKSPACE_DIRECTORY}" && \
    colcon mixin add default "https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml" && \
    colcon mixin update default && \
    mkdir -p "${HOME}/.colcon" && \
    echo "build: {mixin: [compile-commands]}" >> "${HOME}/.colcon/defaults.yaml"
