FROM rwthika/ros2:humble-desktop-full-v24.08

# Use bash as shell.
SHELL ["/bin/bash", "-c"]

#########################################################################################################
# Create a non-root user:                                                                               #
# - https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user.  #
#########################################################################################################
ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

RUN groupadd --gid ${USER_GID} ${USERNAME} && \
    useradd --uid ${USER_UID} --gid ${USER_GID} -m $USERNAME && \
    apt-get update && \
    apt-get install -y sudo && \
    echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

# Activate the previously created user.
USER ${USERNAME}
# Set our working directory.
WORKDIR "/workspaces"
# Ensure we can read/write to the working directory.
RUN sudo chmod a+rwx .

ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

#########################################################################################################
# Update and install required apt and pip dependencies.                                                 #
#########################################################################################################
RUN sudo apt-get update && sudo apt-get upgrade -y

#########################################################################################################
# Install Unitree related stuff.                                                                        #
#########################################################################################################
RUN cd ~ && \
    git clone https://github.com/eclipse-cyclonedds/cyclonedds -b releases/0.10.x && \
    cd cyclonedds && \
    mkdir build install && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=../install && \
    cmake --build . --target install

ENV CYCLONEDDS_HOME="/home/${USERNAME}/cyclonedds/install"

RUN cd ~ && \
    git clone https://github.com/unitreerobotics/unitree_sdk2_python.git && \
    cd unitree_sdk2_python && \
    pip install -e .

#########################################################################################################
# Setup ROS2.                                                                                           #
#########################################################################################################
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc